function aiLabel = query_ai_labeler(jsonPayload)
% QUERY_AI_LABELER  Call LLM endpoint to classify transient regime.
%   aiLabel = query_ai_labeler(jsonPayload) sends the simulation
%   feature JSON to an LLM (OpenAI‑compatible) and returns a struct
%   with fields:
%       regime_classification   (string)
%       safety_margin_pct        (float)
%       confidence_score         (float 0..1)

    apiUrl = 'https://api.openai.com/v1/chat/completions';
    apiKey = getenv('OPENAI_API_KEY');   % Set in environment

    headers = [
        httpHeader('Content-Type', 'application/json')
        httpHeader('Authorization', ['Bearer ' apiKey])
    ];

    % System prompt: enforce structured JSON output
    systemPrompt = [ ...
        'You are an expert AI Data Labeling agent specializing in Computational Fluid Dynamics ' ...
        'and system simulation dynamics. You will receive a JSON payload containing ' ...
        'transient simulation parameters. You must output ONLY a valid JSON object containing: ' ...
        '1. "regime_classification": string ("Safe Operation", "Water Hammer Surge", or "Cavitation Risk"). ' ...
        '2. "safety_margin_pct": float ' ...
        '3. "confidence_score": float (0.0 to 1.0). ' ...
        'Do not provide conversational text. Only output valid JSON.' ...
    ];

    requestBody = struct(...
        'model', 'gpt-4o', ...
        'messages', {{ ...
            struct('role', 'system', 'content', systemPrompt), ...
            struct('role', 'user', 'content', jsonPayload) ...
        }}, ...
        'response_format', struct('type', 'json_object') ...
    );

    options = weboptions('HeaderFields', headers, ...
                         'MediaType', 'application/json', ...
                         'Timeout', 30);

    try
        response = webwrite(apiUrl, requestBody, options);
        aiLabel  = jsondecode(response.choices{1}.message.content);
    catch ME
        warning('API Call failed. Falling back to manual review.');
        aiLabel = struct('regime_classification', 'Unknown', ...
                         'safety_margin_pct', 0.0, ...
                         'confidence_score', 0.0);
    end
end